rails/many-to-many/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles
  resources :authors

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails/many-to-many/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/many-to-many/app/models/article.rb
class Article < ApplicationRecord
  has_and_belongs_to_many :authors
end

rails/many-to-many/app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :articles
end

rails/many-to-many/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails/many-to-many/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to @article
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

rails/many-to-many/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
  end

  def create
    @author = Author.new(author_params)
    @author.save

    redirect_to @author
  end

  private

  def author_params
    params.require(:author).permit(:name)
  end
end

rails/many-to-many/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

rails/many-to-many/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/many-to-many/app/helpers/articles_helper.rb
module ArticlesHelper
end

rails/many-to-many/app/helpers/authors_helper.rb
module AuthorsHelper
end

rails/many-to-many/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rails/many-to-many/app/views/articles/index.html.erb
<h1>Articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Authors</th>
    <th></th>
  </tr>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= article.authors.size %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

<div>
  <%= link_to 'New Article', new_article_path %>
</div>

rails/many-to-many/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

rails/many-to-many/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<ul>
  <% @article.authors.each do |author| %>
    <li><%= author.name %></li>
  <% end %>
</ul>

rails/many-to-many/app/views/authors/index.html.erb
<h1>Authors</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>
  <% @authors.each do |author| %>
    <tr>
      <td><%= author.name %></td>
      <td><%= link_to 'Show', author_path(author) %></td>
    </tr>
  <% end %>
</table>

<div>
  <%= link_to 'New Author', new_author_path %>
</div>

rails/many-to-many/app/views/authors/new.html.erb
<h1>New Author</h1>

<%= form_with scope: :author, url: authors_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

rails/many-to-many/app/views/authors/show.html.erb
<p>
  <strong>name:</strong>
  <%= @author.name %>
</p>

rails/many-to-many/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManyToMany</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails/many-to-many/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to "articles", articles_path %>

<%= link_to "authors", authors_url %>

<h2>Todo</h2>
<ul>
  <li>
    article 을 삭제할때 relation 도 같이 삭제 할 수 있는가?
    <ul>
      <li>article.delete 로 해봤다. author.articles 하면 안나온다.</li>
      <li>그런데... join table 에 가보면 관계는 여전히 남아 있다.</li>
      <li>Sqlite 잘 모르겠다. MySql 로 확인해 보자.</li>
      <li>여튼 article.authors.clear 하면 다 날려준다.</li>
    </ul>
  </li>
</ul>

<h2>Done</h2>
<ul>
  <li>목록을 가지고 올때 include 를 할 수 있는가? article 목록에서 author 숫자 표시 </li>
</ul>